matrix:
  include:
    - language: python
      python: "3.6"
      install:
        - pip install flake8
      script:
        - flake8 --max-line-length 99 api

    - language: node_js
      node_js: 7
      install:
        - npm install eslint --prefix ./frontend
        - npm install babel-eslint --prefix ./frontend
      script:
        - cd frontend
        - ./node_modules/.bin/eslint src/*.js

notifications:
  email:
    recipients:
      - fabrizio@tryolabs.com
    on_success: always
    on_failure: always
