version: "2"

services:

  api:
    build:
      context: .
      dockerfile: deploy/api.docker
    ports:
      - 5000:5000
    volumes:
      - ./api:/api
    env_file:
      - deploy/api.env

  frontend:
    build:
      context: .
      dockerfile: deploy/frontend.docker
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/src/app
      - /src/app/node_modules
    env_file:
      - deploy/frontend.env
